version: 2
updates:
  - package-ecosystem: docker
    directory: caddy
    schedule:
      interval: weekly
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
