services:
  caddy:
    build: caddy
    image: scarif-caddy
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - caddy-config:/config
      - caddy-data:/data
    working_dir: /etc/caddy

  kuma:
    image: louislam/uptime-kuma:2.0.2
    restart: unless-stopped
    volumes:
      - /home/rocky/kuma:/app/data

volumes:
  caddy-config:
  caddy-data:
